stages:
  - clone

clone_repo:
  stage: clone
  script:
    - git clone https://gitlab.com/nanuchi/gitlab-cicd-crash-course.git
    - cd gitlab-cicd-crash-course
    # Additional commands for the pipeline (e.g., testing, deployment, etc.)
